//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GucQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mehsul
    {
        public int mehsul_id { get; set; }
        public string mehsulun_adi { get; set; }
        public string mehsulun_linki { get; set; }
        public string mehsulun_sekli { get; set; }
        public string mehsul_qiymeti { get; set; }
        public Nullable<int> mehsul_price { get; set; }
    }
}
