//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GucQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sifari
    {
        public int sifaris_id { get; set; }
        public string sifarisci_ad_soyad { get; set; }
        public string sifarisci_telefon { get; set; }
        public string sifarisci_unvani { get; set; }
        public Nullable<System.DateTime> sifaris_tarixi { get; set; }
        public Nullable<int> sifaris_novu_id { get; set; }
        public string sifaris_mehsul_adi { get; set; }
        public string sifaris_qeyd { get; set; }
        public string sifaris_qiymet { get; set; }
    
        public virtual SifarisNovu SifarisNovu { get; set; }
    }
}
